# site settings
title: Rok and Olga's wedding
email: rok.hrzic@gmail.com
description: 24 October 2026, Villa Delbrock (Maastricht)
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Rok Hrzic

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
- DESIGN_PLAN.md
- Gemfile
- Gemfile.lock
